### ISSUE TITLE
[feature] add visualization

### ISSUE THREAD

**Issue by Tata0703** [PathOnAI/LiteMultiAgent#32]
CLI based
frontend

**Comment by danni-z-loggia** [comment]
1. CLI based, 2.simple frontend

**Comment by IBMC265** [comment]
https://github.com/PathOnAI/LiteMultiAgent/blob/agent_refactor/visualization.py

**Comment by IBMC265** [comment]
initial version: https://github.com/PathOnAI/LiteMultiAgent/blob/main/visualization.py

**Comment by Tata0703** [comment]
![image](https://github.com/user-attachments/assets/f96708e6-77ed-4886-9618-cf90ffd35ce5)

**Comment by Tata0703** [comment]
https://github.com/PathOnAI/LiteMultiAgent/pull/86
